
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
markdown: kramdown

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: assets/css

collections:
  works: